name: cheminf_tutorial

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - rdkit
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pip